name: My-GitHubActions


on: [commit_comment]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:

      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      



